version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: scraper
      POSTGRES_PASSWORD: scraper
      POSTGRES_DB: scraper_db
    ports:
      - "5432:5432"
  app:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg://scraper:scraper@db:5432/scraper_db
      BASE_URL: https://quotes.toscrape.com
      PAGES: 3
    depends_on:
      - db
      